name: Linux Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run-test-script
        run: ./bash-functions-lib-tests.sh
        shell: bash
