name: macOS Tests
on: [push]
jobs:
  run-tests:
    runs-on: macos-12
    steps:
      - name: Install bash 5 via Homebrew 
        run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install bash
      - name: environment
        run: echo "TERM=xterm-256color" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v3
      - name: run-test-script
        run: ./bash-functions-lib-tests.sh
        shell: bash
